#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SCRIPT_DIRECTORY=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
[[ "$ENV_FILE" == ".env" ]] && ENV_FILE="$SCRIPT_DIRECTORY/stack.env"

require_value() {
  local key="$1" prompt="$2"
  while [[ -z "${!key:-}" ]]; do ask "$key" "$prompt"; done
}

random_hex() {
  openssl rand -hex "$1"
}

banner "Relay on Umbrel Portainer"

stage "Deployment identity"
say "Run this on your computer, not over SSH on UmbrelOS."
say "Umbrel's Portainer uses a nested Docker daemon, so Relay uses named volumes only."
require_value RELAY_IMAGE "Docker Hub image (for example account/relay:latest):"
ask RELAY_HOSTNAME "Public hostname [relay.hades.ws]:"
RELAY_HOSTNAME=${RELAY_HOSTNAME:-relay.hades.ws}
ask RELAY_PORT "Published Umbrel port [9095]:"
RELAY_PORT=${RELAY_PORT:-9095}
[[ "$RELAY_PORT" =~ ^[0-9]+$ ]] || { printf 'Port must be numeric\n' >&2; exit 2; }

stage "Application secrets"
command -v openssl >/dev/null || { printf 'openssl is required\n' >&2; exit 2; }
POSTGRES_PASSWORD=$(_existing POSTGRES_PASSWORD || random_hex 32)
DATABASE_URL=$(_existing DATABASE_URL || true)
DATABASE_URL=${DATABASE_URL:-postgres://relay:$POSTGRES_PASSWORD@postgres:5432/relay}
BETTER_AUTH_SECRET=$(_existing BETTER_AUTH_SECRET || random_hex 48)
RELAY_REALTIME_SECRET=$(_existing RELAY_REALTIME_SECRET || random_hex 48)
say "Generated independent database, authentication, and realtime values."
note "They will be stored only in the gitignored stack.env file and Portainer's stack settings."

stage "GitHub App credentials"
require_value RELAY_GITHUB_APP_ID "GitHub App ID:"
RELAY_GITHUB_PRIVATE_KEY=$(_existing RELAY_GITHUB_PRIVATE_KEY || true)
if [[ -z "$RELAY_GITHUB_PRIVATE_KEY" ]]; then
  while true; do
    ask RELAY_GITHUB_PRIVATE_KEY_SOURCE "Path to the downloaded GitHub App private-key PEM:"
    if [[ -f "$RELAY_GITHUB_PRIVATE_KEY_SOURCE" ]] && grep -q 'BEGIN .*PRIVATE KEY' "$RELAY_GITHUB_PRIVATE_KEY_SOURCE"; then
      break
    fi
    warn "That file is missing or does not look like a private-key PEM."
  done
  RELAY_GITHUB_PRIVATE_KEY=$(awk 'BEGIN { ORS="\\n" } { print }' "$RELAY_GITHUB_PRIVATE_KEY_SOURCE")
fi
RELAY_GITHUB_WEBHOOK_SECRET=$(_existing RELAY_GITHUB_WEBHOOK_SECRET || true)
if [[ -z "$RELAY_GITHUB_WEBHOOK_SECRET" ]]; then
  RELAY_GITHUB_WEBHOOK_SECRET=$(random_hex 48)
  warn "A webhook secret was generated. Copy it from stack.env into the GitHub App."
fi
step "Set the GitHub App webhook URL to https://$RELAY_HOSTNAME/api/github/webhooks"
step "Set the App's webhook secret to RELAY_GITHUB_WEBHOOK_SECRET from stack.env."

stage "Write Portainer variables"
write_env RELAY_IMAGE "$RELAY_IMAGE"
write_env RELAY_HOSTNAME "$RELAY_HOSTNAME"
write_env RELAY_BIND_ADDRESS 0.0.0.0
write_env RELAY_PORT "$RELAY_PORT"
write_env POSTGRES_DB relay
write_env POSTGRES_USER relay
write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
write_env DATABASE_URL "$DATABASE_URL"
write_env BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"
write_env RELAY_REALTIME_SECRET "$RELAY_REALTIME_SECRET"
write_env RELAY_INVITATION_DELIVERY_MODE manual
write_env RELAY_EMAIL_DELIVERY_URL ""
write_env RELAY_GITHUB_APP_ID "$RELAY_GITHUB_APP_ID"
write_env RELAY_GITHUB_PRIVATE_KEY "$RELAY_GITHUB_PRIVATE_KEY"
write_env RELAY_GITHUB_WEBHOOK_SECRET "$RELAY_GITHUB_WEBHOOK_SECRET"
write_env RELAY_CODEX_BIN codex
write_env RELAY_JITSI_BASE_URL https://meet.jit.si
write_env RELAY_JITSI_EMBED_ENABLED false
write_env RELAY_BACKUP_INTERVAL_SECONDS 86400
write_env RELAY_BACKUP_RETENTION_DAYS 14
write_env RELAY_EVALUATION_RETENTION_INTERVAL_SECONDS 3600
chmod 0600 "$ENV_FILE"

stage "Deploy in Portainer"
step "In Umbrel Portainer, create a Git repository stack using compose.portainer.yaml."
step "Load or paste every variable from $ENV_FILE into the stack environment."
step "Deploy, then confirm postgres is healthy, migrate exits 0, and web/worker/backup/retention run."
step "Open http://192.168.0.112:$RELAY_PORT/health before testing relay.hades.ws."
warn "The database and local backups are named volumes inside Umbrel Portainer. Do not convert them to bind mounts."
pause "Press Enter for the summary."

finish
