#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the repeatable two-member MVP pilot proof.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "Relay two-member MVP pilot proof"

stage "Automated safety gates"
say "First prove the deterministic authentication, realtime, worker-loss, and GitHub safety contracts."
step "Ensure Docker or TEST_DATABASE_URL points at a disposable PostgreSQL instance."
step "The GitHub contract test is separate and must target a disposable protected repository."
npm run check
npm test
note "Run npm run test:github-contract separately when its dedicated App variables are available."
pause "The deterministic gates passed and any contract-test evidence is saved?"

stage "Two authenticated Pilot members"
say "Use two separate browser profiles so each Pilot member has an independent session."
ask RELAY_URL "Relay URL (for example https://relay.example.com):"
open_url "$RELAY_URL"
step "In profile A, sign in as the Provider account owner."
step "In profile B, sign in as the invited, verified Pilot member."
step "Confirm both views show the same Project, Shared agent channel, two humans, and Alex."
pause "Both distinct Pilot identities can see the Shared agent channel?"

stage "Rejected and accepted delegation"
say "Keep the collaborator connected while the owner proves mention readiness and attribution."
step "Temporarily make one readiness condition unavailable, then post an explicit @Alex request."
step "Confirm the Message remains visible as rejected and no Task or AgentRun appears."
step "Restore readiness, then have the owner post a real, scoped @Alex engineering request."
step "Confirm both profiles see it queued once; reload profile A and confirm it still appears once."
pause "The owner's real delegation is queued with correct attribution?"

stage "Clarification across members"
say "The collaborator must continue the owner's existing work instead of creating another Task."
step "When Alex asks a clarification, close profile A completely."
step "In profile B, answer the clarification as a direct reply."
step "Confirm the same AgentRun returns to queued or working and no second Task appears."
step "Ask for progress through the ordinary composer and confirm only a concise projection appears."
pause "The collaborator resumed the owner's AgentRun with attributable input?"

stage "Independent collaborator delegation"
say "Now prove that shared Provider ownership does not prevent independent delegation."
step "After capacity is available, have profile B post a different real @Alex engineering request."
step "Confirm profile B is the request author and both profiles converge on its status."
step "Exercise a disposable cancellation request and retain its cancellation evidence."
step "Retain one understandable failed-run example without deleting its history."
pause "The collaborator delegated independently and cancellation/failure evidence is visible?"

stage "Realtime and web replacement"
say "Prove realtime is acceleration only; PostgreSQL remains authoritative."
step "Disconnect one browser, let the other create updates, then reconnect the first."
step "Drop one wake-up and deliver a duplicate wake-up with browser network tooling."
step "Confirm reconciliation restores missing events and creates no duplicate Channel entries."
step "While an AgentRun is active, replace only web with: ops/deploy.sh web"
step "Confirm worker execution continues and both profiles converge after reconnect."
pause "Browser and web-process loss preserved execution and a single history?"

stage "Worker-loss boundaries"
say "Use only disposable pilot requests and the Linked pilot repository's run-specific branch."
warn "Unknown-boundary loss can leave real repository side effects; never replay or manually requeue it."
step "Exercise the tested known-boundary recovery path and confirm one Provider turn/repository effect."
step "For an unknown active boundary, confirm the run is disposable before forcing worker loss."
if confirm "Force the pre-agreed disposable worker-loss exercise now?"; then
  docker compose kill --signal KILL worker
  docker compose start worker
else
  warn "Worker-loss exercise skipped; the durable verifier will remain incomplete."
fi
step "Wait for lease expiry, then confirm recovering becomes paused for human review."
step "Confirm no duplicate Provider turn, branch update, commit, or pull request was created."
pause "Known and unknown worker-loss evidence is retained?"

stage "Pull-request review and durable verification"
say "Finish with a real completed Artifact and an auditable report."
step "Allow at least one real request to complete and open its pull-request Artifact in GitHub."
step "A human other than the last pusher must confirm it is suitable for review; do not merge in Relay."
step "Review the automated authorization results for invitation binding, revocation, owner-only management, cross-Workspace access, and WebSocket rejection."
step "The verifier exits non-zero until every durable pilot gate is present."
docker compose exec web npm run start:verify-pilot
finish
